# Site settings
course_name: Intorduction to Computer Vision
course_description: "Computer vision is one of the major research fields of artificial intelligence, with many applications in image understanding and processing, medical care, autonomous driving, and robotics. We offer this undergraduate course to provide a comprehensive introduction to the basic concepts of computer vision and its broad applications. In this course, we will cover both the traditional non-learning methods (e.g. classic descriptors, multiview geometry) and deep learning based methods from a modern perspective, where 3D vision serves as a natural bridge.The objective of this course is thus to consolidate the fundemantals, depict a full picture of this field, and get the students prepared for doing frontier research in computer vision. During this course, students will learn to build a basic vision system and implement and train their own neural networks to process and analyze 2D and 3D visual data."
course_semester: "Spring 2022"

baseurl: "/IntrotoCV/" # the subpath of your site, e.g. /blog/
url: "https://hughw19.github.io" # the base hostname & protocol for your site

schoolname: "Peking University"
schoolurl: "https://www.pku.edu.cn/"
#twitter_username: username 

address: |
    Center on Frontiers of Computing Studies, 
    Peking University,
    Beijing, China

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
